import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import esmock from 'esmock';
test('Live layouts preserve drafts, sort conversations by activity and expand one kin at a time', async()=>{
 const dom=new JSDOM('<div id="app"></div><div id="notice"></div>',{url:'https://example.org/'});
 dom.window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};
 dom.window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new dom.window.Event('close'))};
 for(const key of ['document','location','history','sessionStorage','localStorage','FormData'])globalThis[key]=dom.window[key];
 const me='22222222-2222-4222-8222-222222222222', amy='11111111-1111-4111-8111-111111111111',zoe='33333333-3333-4333-8333-333333333333';
 const people=[{id:me,name:'Me'},{id:zoe,name:'Zoe'},{id:amy,name:'amy'}];
 const tables={hearth_events:[{id:'plan',owner:me,title:'Tea',place:'Garden',starts_at:'2099-01-01',ends_at:'2099-01-02'}],hearth_event_invites:[{event:'plan',person:amy},{event:'plan',person:zoe}],hearth_statuses:[{id:'moment',author:zoe,content:'Sunshine in the garden',topic:'Outdoors',audience:'All kin',created_at:'2026-09-17T10:00:00Z'}],hearth_kin_groups:[{id:'family',name:'Family'}],hearth_kin_group_members:[],hearth_profiles:people,hearth_connections:[{requester:me,recipient:zoe,accepted:true},{requester:amy,recipient:me,accepted:true}],hearth_circle:[{owner:me,member:amy}],hearth_preferences:{topics:['Outdoors'],update_mode:'manual'}};
 let savedPlan;const writes=[];
 const client={auth:{onAuthStateChange(){},async getSession(){return{data:{session:{user:{id:me}}}}}},async rpc(action,args){if(action==='hearth_save_event')savedPlan=args;return{data:action==='hearth_sent_introductions'?[{id:'sent',a:zoe,b:amy,a_name:'Zoe',b_name:'amy',created_at:'2026-09-17T10:00:00Z'}]:action==='hearth_event_attendees'?[]:null}},from(table){let single=false,filter='';const q={upsert(value){writes.push([table,value]);return q},insert(value){writes.push([table,value]);return q},or(value){filter=value;return q},select(){return q},eq(){return q},neq(){return q},order(){return q},gte(){return q},limit(){return q},range(){return q},in(){return q},maybeSingle(){single=true;return q},then(resolve){return Promise.resolve({data:table==='hearth_messages'&&filter?[{created_at:filter.includes(zoe)?'2026-09-17T10:00:00Z':'2026-09-16T10:00:00Z'}]:table==='hearth_profiles'&&single?people[0]:tables[table]??(single?null:[])}).then(resolve)}};return q}};
 globalThis.fetch=async()=>({ok:true,json:async()=>({supabaseUrl:'https://example.supabase.co',supabasePublishableKey:'public'})});
 await esmock('../../js/live/app.js',{'@supabase/supabase-js':{createClient:()=>client}});
 const settle=()=>new Promise(r=>setTimeout(r,20));await settle();
 assert.equal(document.querySelector('.live-companions .kin-row'),null);
 document.querySelector('.sidebar [data-tab="parlor"]').click();await settle();
 document.querySelector('[data-chat="'+zoe+'"]').click();await settle();
 assert.match(document.querySelector('#conversation h2').textContent,/Zoe/);
 assert.equal(document.querySelector('#peer'),null);
 assert.ok(document.querySelector('#conversation [data-sent-introduction="sent"]'));
 assert.match(document.querySelector('#conversation .sent-introduction').textContent,/Hi Zoe! I noticed you and amy/);
 assert.deepEqual([...document.querySelectorAll('.parlor-person strong')].map(e=>e.textContent),['Zoe','amy']);
 assert.equal(document.querySelector('.circle-marker'),null);
 assert.ok(document.querySelector('.chat-layout-live'));
 assert.equal(document.querySelector('#conversation [data-action="lock"]'),null);
 const input=document.querySelector('#kin-search');input.focus();input.value='ZO';input.dispatchEvent(new dom.window.Event('input',{bubbles:true}));
 assert.equal(document.activeElement,input);
 assert.equal(document.querySelectorAll('.parlor-person').length,1);
 document.querySelector('.parlor-person').click();await settle();
 assert.match(document.querySelector('#conversation h2').textContent,/Zoe/);
 assert.ok(document.querySelector('#unlock'));
 assert.equal(document.querySelector('#unlock input[type=password]'),null);
 assert.ok(document.querySelector('#unlock [name=saved]').required);
 assert.equal(document.querySelector('#unlock [name=remember]').checked,false);
 assert.match(document.querySelector('#unlock textarea').value,/^([0-9a-f]{8}-){7}[0-9a-f]{8}$/);
 assert.equal(document.querySelector('.parlor-person').getAttribute('aria-pressed'),'true');

 document.querySelector('.sidebar [data-tab="gatherings"]').click();await settle();
 assert.equal(document.querySelector('#event-composer').hidden,true);
 document.querySelector('[data-action="toggle-event"]').click();
 assert.equal(document.querySelector('#event-composer').hidden,false);
 const title=document.querySelector('#event [name="title"]');title.value='Tea together';title.dispatchEvent(new dom.window.Event('input',{bubbles:true}));
 document.querySelector('[data-event-guest="'+amy+'"]').click();
 assert.equal(document.querySelector('#event [name="title"]'),title);
 assert.equal(title.value,'Tea together');
 assert.match(document.querySelector('#event-who').textContent,/amy/);
 assert.equal(document.querySelector('[data-event-guest="'+amy+'"]').getAttribute('aria-pressed'),'true');
 document.querySelector('#event [name="place"]').value='The garden';
 document.querySelector('[data-action="choose-event-time"]').click();
 document.querySelector('#event-time-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
 document.querySelector('#event').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await settle();
 assert.equal(savedPlan.plan_title,'Tea together');
 assert.deepEqual(savedPlan.invitees,[amy]);

 document.querySelector('.sidebar [data-tab="kin"]').click();await settle();
 assert.equal(document.querySelectorAll('.kin-sidebar > .panel.parlor-kin').length,3);
 assert.equal(document.querySelector('.kin-growth-grid'),null);
 dom.window.HTMLElement.prototype.scrollIntoView=function(){this.dataset.scrolled='true'};
 document.querySelector('[data-growth="group"]').click();
 const groupCard=document.querySelector('#kin-group-detail');
 assert.ok(groupCard.previousElementSibling.querySelector('#friend'));
 assert.ok(groupCard.nextElementSibling.id.startsWith('kin-card-'));
 assert.equal(groupCard.querySelector('#group-edit').open,false);
 document.querySelector('#kin-card-list [data-kin-card="'+amy+'"]').click();
 const card=document.querySelector('#kin-card-'+amy);
 assert.equal(card.dataset.scrolled,'true');assert.equal(document.activeElement,card);
 assert.ok(card.classList.contains('kin-detail-selected'));
 assert.equal(card.querySelector('[data-chat]').textContent,'Visit the parlor');
 assert.equal(card.querySelector('[id^="kin-options-"]').hidden,false);
 card.querySelector('[data-chat]').click();await settle();
 assert.match(document.querySelector('#conversation h2').textContent,/amy/);
 document.querySelector('.sidebar [data-tab="kin"]').click();await settle();
 document.querySelector('[data-kin-expand="'+zoe+'"]').click();
 assert.equal(document.querySelector('#kin-options-'+amy).hidden,true);
 assert.equal(document.querySelector('#kin-options-'+zoe).hidden,false);
 assert.match(document.querySelector('#kin-groups h2').textContent,/Zoe’s groups/);
 document.querySelector('.sidebar [data-tab="pulse"]').click();await settle();
 assert.equal(document.querySelector('[data-feed-filter]'),null);
 assert.equal(document.querySelector('#moment-composer').hidden,true);
 document.querySelector('[data-action="toggle-moment"]').click();
 const draft=document.querySelector('#status textarea');draft.value='A quiet afternoon';draft.dispatchEvent(new dom.window.Event('input',{bubbles:true}));
 document.querySelector('[data-action="toggle-moment"]').click();
 document.querySelector('[data-action="toggle-moment"]').click();
 assert.equal(document.querySelector('#status textarea').value,'A quiet afternoon');
 const topic=document.querySelector('#status select[name="topic"]');
 const audiences=[...document.querySelector('#status select[name="audience"]').options];
 assert.deepEqual(audiences.map(o=>o.textContent),['Me','All kin','Family']);
 assert.deepEqual(audiences.map(o=>o.value),['Only me','All kin','group:family']);
 assert.equal(topic.hidden,true);
 topic.closest('.soft-choice').querySelector('[data-soft-toggle]').click();
 topic.closest('.soft-choice').querySelector('[data-soft-option="Outdoors"]').click();
 assert.equal(new FormData(document.querySelector('#status')).get('topic'),'Outdoors');
 assert.equal(topic.closest('.soft-choice').querySelector('.soft-options').hidden,true);
 document.querySelector('.sidebar [data-tab="settings"]').click();await settle();
 assert.ok(document.querySelector('[data-action="lock"]'));
 assert.ok(document.querySelector('[data-feed-filter]'));
 const beforeWrites=writes.length;
 document.querySelector('[data-topic="Little joys"]').click();
 document.querySelector('[data-topic="Making things"]').click();
 assert.equal(writes.length,beforeWrites);
 document.querySelector('[data-action="apply-feed"]').click();await settle();
 assert.equal(writes.length,beforeWrites+1);
 assert.deepEqual(writes.at(-1)[1].topics,['Outdoors','Little joys','Making things']);
 assert.ok([...document.querySelectorAll('select')].every(s=>s.hidden));
 assert.ok(document.querySelector('.page-layout > .preferences-layout'));
 assert.equal(document.querySelector('#photo-name').textContent,'Choose file');
 assert.equal(document.querySelector('#profile-photo').type,'file');
 document.querySelector('.sidebar [data-tab="pulse"]').click();await settle();
 assert.equal(document.querySelector('#status textarea').value,'A quiet afternoon');
 assert.equal(document.querySelector('#status select[name="topic"]').value,'Outdoors');
 document.querySelector('[data-hide-moment="moment"]').click();await settle();
 assert.equal(document.querySelector('[data-hide-moment="moment"]'),null);
 assert.deepEqual(JSON.parse(localStorage.getItem('hearth-hidden:'+me)),['moment']);
 document.querySelector('.sidebar [data-tab="settings"]').click();await settle();
 document.querySelector('[data-action="restore-moments"]').click();await settle();
 document.querySelector('.sidebar [data-tab="pulse"]').click();await settle();
 assert.ok(document.querySelector('[data-hide-moment="moment"]'));
 document.querySelector('[data-love="moment"]').click();await settle();
 assert.match(document.querySelector('#conversation h2').textContent,/Zoe/);
 assert.ok(document.querySelector('#unlock'));
 document.querySelector('.sidebar [data-tab="gatherings"]').click();await settle();
 document.querySelector('[data-message-guest="plan"]').click();
 assert.equal(document.querySelectorAll('#gathering-guests [data-chat]').length,2);
 document.querySelector('[data-message-all="plan"]').click();
 const note=document.querySelector('[data-gathering-note="plan"]');
 note.querySelector('textarea').value='Bring a cake';
 note.querySelector('textarea').dispatchEvent(new dom.window.Event('input',{bubbles:true}));
 note.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await settle();
 assert.equal(writes.at(-1)[0],'hearth_statuses');
 assert.equal(writes.at(-1)[1].audience,'Gathering');
 assert.equal(writes.at(-1)[1].audience_event,'plan');
 assert.equal(writes.at(-1)[1].content,'Tea\\n\\nBring a cake'.replaceAll('\\n','\n'));
 dom.window.close();
});
